version: '3.8'

services:
  postgres:
    image: postgres:17.0
    container_name: postgres_container
    environment:
      POSTGRES_USER: cleib
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myfirstdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cleib.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5001:80"
    depends_on:
      - postgres

volumes:
  postgres_data: